# yaml 配置实例
version: '3'
services:
  web:
    image: woodlsy/hyperf:2.0
#    build: ./docker/php
    container_name: 'manageApi'
    ports:
      - "9802:9501"
    volumes:
      - ./:/www:rw
#    restart: always
#    command: /bin/bash -c "cd /www && composer update --no-dev"
    entrypoint: ["php", "/www/bin/hyperf.php", "start"]
    tty: true
    privileged: true
    networks:
      - default
  redis:
    image: redis:5.0.3-alpine
    container_name: manageApi-redis
    #ports:
    #  - "6380:6379"
    volumes:
      - ./docker/redis/redis.conf:/etc/redis.conf:rw
      - ./docker/data/redis:/data:rw
#    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
    tty: true
    networks:
      - default
networks:
  default: